name: no-Linter
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - '!**.py'
  workflow_dispatch:
jobs:
  linter:
    runs-on: windows-latest
    steps:
      - name: Success
        run: exit 0
